services:
  postgres:
    image: postgres:17.5
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=task_manager
      - POSTGRES_PASSWORD=admin123@
      - POSTGRES_USER=user_admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge