services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=task_manager
      - POSTGRES_PASSWORD=admin123@
      - POSTGRES_USER=admin  # Changed to admin for consistency
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d task_manager"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: task_manager_app
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/task_manager
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin123@
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge